config/routes.rb
Rails.application.routes.draw do
  

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'

  resources :projects
  resources :users
  get '/signup', to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { email.downcase! }
	validates :name, presence: true, length: {maximum: 30}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 50}, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	has_secure_password

	def User.digest(string)
	    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only:[:new, :create, :edit, :update, :destroy]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @project = Project.new
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

      if @project.save
        ProjectJob.perform_now(@project, false)
        head :ok
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end

  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        flash[:success] = 'Project was successfully updated.'
        format.html { redirect_to root_path}
        format.json { render :show, status: :ok, location: root_path }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    ProjectJob.perform_now(@project, true)

    @project.destroy

    head :no_content
  end


  private
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in first"
        redirect_to login_url
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :url, :desc)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		redirect_to user
  	else
  		flash.now[:danger] = 'Invalid username or password.'
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only:[:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only:[:edit, :update]
  before_action :admin_user, only: :destroy

  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	flash[:success] = "User created successfully!"
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "User updated"
      redirect_to @user
    else
      flash[:danger] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Successfully removed user"
    redirect_to users_url
  end

  private

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in first"
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def log_out
		session.delete(:user_id)
  		@current_user = nil
	end

	def current_user?(user)
    	user == current_user
  	end

	def current_user
		@currrent_user = @current_user ||=  User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>dev</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

  </head>

  <body>
    <div class="header">
      
    </div>
    
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    
    <%= yield %>
    
    <%  debug(params) if Rails.env.development? %>

    <footer class="footer">
    <div class="container">
      <% if logged_in? %>
        <%= current_user.name %>
        <%= link_to "Home", root_path() %>
        <%= link_to "Profile", user_path(current_user) %>
        <%= link_to "Users", users_path() %>
        <%= link_to "Log out", logout_path, method: :delete %>
      <% else %>
        <%= link_to "Log in", login_path %>
      <% end %>
    </div>
    </footer>

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project_form.html.erb
<%= form_for project, remote: true, authenticity_token: true do |f| %>
  <%= f.label :project_name, "Project name:" %>
  <%= f.text_field :name, class: "form-control", data: {textarea: "name"} %>

  <%= f.label :project_url, "Url: (ex. http://www.example.com)" %>
  <%= f.text_field :url, class: "form-control", data: {textarea: "url"} %>

  <%= f.label :project_desc, "Description" %>
  <%= f.text_area :desc, class: "form-control", data: {textarea: "desc"} %>

  <%= f.submit "send", data: {send: "name, url, desc"} %>
<% end %>

app/views/projects/_projects.html.erb
<% projects.each do |p| %>
  <div id="pro_<%=p.id%>" class="project">
    <b><%= p.name %></b>
    <%= simple_format(p.desc) %>
    <%= link_to "Go to website", p.url %>
    <% if logged_in? %>
     | <%= link_to 'Edit', edit_project_path(p) %>
    <%= link_to 'Destroy', p, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'project_form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
  	<div class="col-sm">
  	 <h3>Hi, my name is Andreas Åker 	</h3>
     <p>Junior web developer</p>
     <h5>Tools i use the most</h5>
     <p>Ruby, Rails, JS, Jquery, HTML, CSS, Sass</p>
	  </div>
  </div>
  <div class="row">
    <div class="col-sm" id="projects">
    <h5>Projects:</h5>
    	<% if @projects.any? %>
  			<%= render partial: "projects/projects", locals: {projects: @projects} %>
		  <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <% if logged_in? %>
        <%= render partial: "projects/project_form", locals: {project: @project} %>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for (@user) do |f| %>
	<%= render 'shared/error_messages' %>


	<%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:button_text, 'Update user') %>
<h3>Edit <%= @user.name %></h3>

<%= render partial: "form" %>

app/views/users/index.html.erb
<ul>
<% @users.each do |u| %>
	<li>
		<%= "#{u.name} #{u.email}"%> | 
		<% if current_user.admin? && !current_user?(u) %>
			<%= link_to "Delete", u, method: :delete, data: {confirm: "You sure?"} %>
		<% end %>
	</li>
<% end %>
</ul>

app/views/users/new.html.erb
<% provide(:button_text, 'Create') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= render partial: 'form' %>

app/views/users/show.html.erb
<p><%= @user.name %></p>
<p><%= @user.email %></p>
<p><%= link_to "Edit user", edit_user_path(@user.id)%></p>
<p>Admin:<%= @user.admin?%></p>